/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type {
  PatchedUser,
  PatchedUserCreate,
  PatchedUserRoleCreate,
  TokenRefresh,
  User,
  UserCreate,
  UserLogin,
  UserLoginRespose,
  UserRegistration,
  UserRegistrationRespose,
  UserRoleCreate
} from '../../model';

import { customAxios } from '../../../lib/axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;




  export const getUser = () => {
const userDetailRetrieve = (
    id: number,
 ) => {
      return customAxios<UserCreate>(
      {url: `/api/user/detail/${id}/`, method: 'GET'
    },
      );
    }
  const userDetailUpdate = (
    id: number,
    userCreate: NonReadonly<UserCreate>,
 ) => {
      return customAxios<UserCreate>(
      {url: `/api/user/detail/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userCreate
    },
      );
    }
  const userDetailPartialUpdate = (
    id: number,
    patchedUserCreate?: NonReadonly<PatchedUserCreate>,
 ) => {
      return customAxios<UserCreate>(
      {url: `/api/user/detail/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedUserCreate
    },
      );
    }
  const userDetailDestroy = (
    id: number,
 ) => {
      return customAxios<void>(
      {url: `/api/user/detail/${id}/`, method: 'DELETE'
    },
      );
    }
  const userListList = (

 ) => {
      return customAxios<UserCreate[]>(
      {url: `/api/user/list/`, method: 'GET'
    },
      );
    }
  const userListCreate = (
    userCreate: NonReadonly<UserCreate>,
 ) => {
      return customAxios<UserCreate>(
      {url: `/api/user/list/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate
    },
      );
    }
  const userLoginCreate = (
    userLogin: UserLogin,
 ) => {
      return customAxios<UserLoginRespose>(
      {url: `/api/user/login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLogin
    },
      );
    }
  const userLogoutCreate = (

 ) => {
      return customAxios<void>(
      {url: `/api/user/logout/`, method: 'POST'
    },
      );
    }
  /**
 * GET - Obtener usuario actual
 */
const userMeRetrieve = (

 ) => {
      return customAxios<User>(
      {url: `/api/user/me/`, method: 'GET'
    },
      );
    }
  /**
 * PUT - Actualizar usuario completo
 */
const userMeUpdate = (
    user: NonReadonly<User>,
 ) => {
      return customAxios<User>(
      {url: `/api/user/me/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: user
    },
      );
    }
  /**
 * PATCH - Actualizar usuario parcialmente
 */
const userMePartialUpdate = (
    patchedUser?: NonReadonly<PatchedUser>,
 ) => {
      return customAxios<User>(
      {url: `/api/user/me/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedUser
    },
      );
    }
  const userRegisterCreate = (
    userRegistration: NonReadonly<UserRegistration>,
 ) => {
      return customAxios<UserRegistrationRespose>(
      {url: `/api/user/register/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegistration
    },
      );
    }
  const userRolesList = (

 ) => {
      return customAxios<UserRoleCreate[]>(
      {url: `/api/user/roles/`, method: 'GET'
    },
      );
    }
  const userRolesCreate = (
    userRoleCreate: NonReadonly<UserRoleCreate>,
 ) => {
      return customAxios<UserRoleCreate>(
      {url: `/api/user/roles/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRoleCreate
    },
      );
    }
  const userRolesUpdate = (
    userRoleCreate: NonReadonly<UserRoleCreate>,
 ) => {
      return customAxios<UserRoleCreate>(
      {url: `/api/user/roles/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userRoleCreate
    },
      );
    }
  const userRolesPartialUpdate = (
    patchedUserRoleCreate?: NonReadonly<PatchedUserRoleCreate>,
 ) => {
      return customAxios<UserRoleCreate>(
      {url: `/api/user/roles/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedUserRoleCreate
    },
      );
    }
  /**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
const userTokenRefreshCreate = (
    tokenRefresh: NonReadonly<TokenRefresh>,
 ) => {
      return customAxios<TokenRefresh>(
      {url: `/api/user/token/refresh/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefresh
    },
      );
    }
  return {userDetailRetrieve,
          userDetailUpdate,
          userDetailPartialUpdate,
          userDetailDestroy,userListList,
          userListCreate,userLoginCreate,
          userLogoutCreate,userMeRetrieve,
          userMeUpdate,userMePartialUpdate,
          userRegisterCreate,userRolesList,
          userRolesCreate,userRolesUpdate,
          userRolesPartialUpdate,
          userTokenRefreshCreate}};
