/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type {
  SchemaRetrieve200Four,
  SchemaRetrieve200One,
  SchemaRetrieve200Three,
  SchemaRetrieve200Two,
  SchemaRetrieveParams
} from '../../model';

import { customAxios } from '../../../lib/axios';



  export const getSchema = () => {
/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.

- YAML: application/vnd.oai.openapi
- JSON: application/vnd.oai.openapi+json
 */
const schemaRetrieve = (
    params?: SchemaRetrieveParams,
 ) => {
      return customAxios<SchemaRetrieve200One | SchemaRetrieve200Two | SchemaRetrieve200Three | SchemaRetrieve200Four>(
      {url: `/api/schema/`, method: 'GET',
        params
    },
      );
    }
  return {schemaRetrieve}};
export type SchemaRetrieveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSchema>['schemaRetrieve']>>>
