/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type {
  Client,
  ClientCreate,
  PatchedClient
} from '../../model';

import { customAxios } from '../../../lib/axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;




  export const getTenant = () => {
const tenantClientsList = (

 ) => {
      return customAxios<Client[]>(
      {url: `/api/tenant/clients/`, method: 'GET'
    },
      );
    }
  const tenantClientsCreate = (
    clientCreate: NonReadonly<ClientCreate>,
 ) => {
      return customAxios<ClientCreate>(
      {url: `/api/tenant/clients/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clientCreate
    },
      );
    }
  const tenantClientsRetrieve = (
    id: number,
 ) => {
      return customAxios<Client>(
      {url: `/api/tenant/clients/${id}/`, method: 'GET'
    },
      );
    }
  const tenantClientsUpdate = (
    id: number,
    client: NonReadonly<Client>,
 ) => {
      return customAxios<Client>(
      {url: `/api/tenant/clients/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: client
    },
      );
    }
  const tenantClientsPartialUpdate = (
    id: number,
    patchedClient?: NonReadonly<PatchedClient>,
 ) => {
      return customAxios<Client>(
      {url: `/api/tenant/clients/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedClient
    },
      );
    }
  const tenantClientsDestroy = (
    id: number,
 ) => {
      return customAxios<void>(
      {url: `/api/tenant/clients/${id}/`, method: 'DELETE'
    },
      );
    }
  const tenantClientsCreateAdminUserCreate = (
    id: number,
    client: NonReadonly<Client>,
 ) => {
      return customAxios<Client>(
      {url: `/api/tenant/clients/${id}/create-admin-user/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: client
    },
      );
    }
  /**
 * Obtener información del tenant actual
 */
const tenantClientsCurrentRetrieve = (

 ) => {
      return customAxios<Client>(
      {url: `/api/tenant/clients/current/`, method: 'GET'
    },
      );
    }
  return {tenantClientsList,tenantClientsCreate,tenantClientsRetrieve,tenantClientsUpdate,tenantClientsPartialUpdate,tenantClientsDestroy,tenantClientsCreateAdminUserCreate,tenantClientsCurrentRetrieve}};
export type TenantClientsListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsList']>>>
export type TenantClientsCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsCreate']>>>
export type TenantClientsRetrieveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsRetrieve']>>>
export type TenantClientsUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsUpdate']>>>
export type TenantClientsPartialUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsPartialUpdate']>>>
export type TenantClientsDestroyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsDestroy']>>>
export type TenantClientsCreateAdminUserCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsCreateAdminUserCreate']>>>
export type TenantClientsCurrentRetrieveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['tenantClientsCurrentRetrieve']>>>
