/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type {
  BaseComponentType,
  BaseMachineState,
  BaseMachineType,
  Batch,
  BatchLinkBase,
  BatchLinkProduction,
  BatchProduction,
  Component,
  ConfigComponentType,
  ConfigMachineState,
  ConfigMachineType,
  ConfigOrderPriority,
  ConfigOrderStatus,
  ConfigProcessType,
  ConfigStepStatus,
  Machine,
  OrderPriority,
  OrderStatus,
  PatchedBaseComponentType,
  PatchedBaseMachineState,
  PatchedBaseMachineType,
  PatchedBatch,
  PatchedBatchLinkProduction,
  PatchedBatchProduction,
  PatchedComponent,
  PatchedMachine,
  PatchedOrderPriority,
  PatchedOrderStatus,
  PatchedProcessCreate,
  PatchedProcessExecution,
  PatchedProcessExecutionProduction,
  PatchedProcessType,
  PatchedProduct,
  PatchedProductionOrder,
  PatchedQualityInspectionBase,
  PatchedQualityInspectionProduction,
  Process,
  ProcessCreate,
  ProcessExecution,
  ProcessExecutionProduction,
  ProcessType,
  Product,
  ProductCreate,
  ProductionOrder,
  ProductionOrderCreate,
  QualityInspectionBase,
  QualityInspectionDetailBase,
  QualityInspectionProduction,
} from "../../model";

import { customAxios } from "../../../lib/axios";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const getManufacturingAPI = () => {
  const manufacturingBatchLinksList = () => {
    return customAxios<BatchLinkBase[]>({
      url: `/api/manufacturing/batch-links/`,
      method: "GET",
    });
  };
  const manufacturingBatchLinksRetrieve = (id: number) => {
    return customAxios<BatchLinkBase>({
      url: `/api/manufacturing/batch-links/${id}/`,
      method: "GET",
    });
  };
  const manufacturingBatchesList = () => {
    return customAxios<Batch[]>({
      url: `/api/manufacturing/batches/`,
      method: "GET",
    });
  };
  const manufacturingBatchesCreate = (batch: NonReadonly<Batch>) => {
    return customAxios<Batch>({
      url: `/api/manufacturing/batches/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batch,
    });
  };
  const manufacturingBatchesRetrieve = (id: number) => {
    return customAxios<Batch>({
      url: `/api/manufacturing/batches/${id}/`,
      method: "GET",
    });
  };
  const manufacturingBatchesUpdate = (
    id: number,
    batch: NonReadonly<Batch>,
  ) => {
    return customAxios<Batch>({
      url: `/api/manufacturing/batches/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: batch,
    });
  };
  const manufacturingBatchesPartialUpdate = (
    id: number,
    patchedBatch?: NonReadonly<PatchedBatch>,
  ) => {
    return customAxios<Batch>({
      url: `/api/manufacturing/batches/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBatch,
    });
  };
  const manufacturingBatchesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/batches/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingComponentTypesList = () => {
    return customAxios<BaseComponentType[]>({
      url: `/api/manufacturing/component-types/`,
      method: "GET",
    });
  };
  const manufacturingComponentTypesCreate = (
    baseComponentType: NonReadonly<BaseComponentType>,
  ) => {
    return customAxios<BaseComponentType>({
      url: `/api/manufacturing/component-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: baseComponentType,
    });
  };
  const manufacturingComponentTypesRetrieve = (id: number) => {
    return customAxios<BaseComponentType>({
      url: `/api/manufacturing/component-types/${id}/`,
      method: "GET",
    });
  };
  const manufacturingComponentTypesUpdate = (
    id: number,
    baseComponentType: NonReadonly<BaseComponentType>,
  ) => {
    return customAxios<BaseComponentType>({
      url: `/api/manufacturing/component-types/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: baseComponentType,
    });
  };
  const manufacturingComponentTypesPartialUpdate = (
    id: number,
    patchedBaseComponentType?: NonReadonly<PatchedBaseComponentType>,
  ) => {
    return customAxios<BaseComponentType>({
      url: `/api/manufacturing/component-types/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBaseComponentType,
    });
  };
  const manufacturingComponentTypesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/component-types/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingComponentsList = () => {
    return customAxios<Component[]>({
      url: `/api/manufacturing/components/`,
      method: "GET",
    });
  };
  const manufacturingComponentsCreate = (component: NonReadonly<Component>) => {
    return customAxios<Component>({
      url: `/api/manufacturing/components/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: component,
    });
  };
  const manufacturingComponentsRetrieve = (id: number) => {
    return customAxios<Component>({
      url: `/api/manufacturing/components/${id}/`,
      method: "GET",
    });
  };
  const manufacturingComponentsUpdate = (
    id: number,
    component: NonReadonly<Component>,
  ) => {
    return customAxios<Component>({
      url: `/api/manufacturing/components/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: component,
    });
  };
  const manufacturingComponentsPartialUpdate = (
    id: number,
    patchedComponent?: NonReadonly<PatchedComponent>,
  ) => {
    return customAxios<Component>({
      url: `/api/manufacturing/components/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedComponent,
    });
  };
  const manufacturingComponentsDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/components/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingConfigComponentTypesList = () => {
    return customAxios<ConfigComponentType[]>({
      url: `/api/manufacturing/config/component-types/`,
      method: "GET",
    });
  };
  const manufacturingConfigComponentTypesCreate = (
    configComponentType: NonReadonly<ConfigComponentType>,
  ) => {
    return customAxios<ConfigComponentType>({
      url: `/api/manufacturing/config/component-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configComponentType,
    });
  };
  const manufacturingConfigMachineStatesList = () => {
    return customAxios<ConfigMachineState[]>({
      url: `/api/manufacturing/config/machine-states/`,
      method: "GET",
    });
  };
  const manufacturingConfigMachineStatesCreate = (
    configMachineState: NonReadonly<ConfigMachineState>,
  ) => {
    return customAxios<ConfigMachineState>({
      url: `/api/manufacturing/config/machine-states/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configMachineState,
    });
  };
  const manufacturingConfigMachineTypesList = () => {
    return customAxios<ConfigMachineType[]>({
      url: `/api/manufacturing/config/machine-types/`,
      method: "GET",
    });
  };
  const manufacturingConfigMachineTypesCreate = (
    configMachineType: NonReadonly<ConfigMachineType>,
  ) => {
    return customAxios<ConfigMachineType>({
      url: `/api/manufacturing/config/machine-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configMachineType,
    });
  };
  const manufacturingConfigOrderPrioritiesList = () => {
    return customAxios<ConfigOrderPriority[]>({
      url: `/api/manufacturing/config/order-priorities/`,
      method: "GET",
    });
  };
  const manufacturingConfigOrderPrioritiesCreate = (
    configOrderPriority: NonReadonly<ConfigOrderPriority>,
  ) => {
    return customAxios<ConfigOrderPriority>({
      url: `/api/manufacturing/config/order-priorities/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configOrderPriority,
    });
  };
  const manufacturingConfigOrderStatusList = () => {
    return customAxios<ConfigOrderStatus[]>({
      url: `/api/manufacturing/config/order-status/`,
      method: "GET",
    });
  };
  const manufacturingConfigOrderStatusCreate = (
    configOrderStatus: NonReadonly<ConfigOrderStatus>,
  ) => {
    return customAxios<ConfigOrderStatus>({
      url: `/api/manufacturing/config/order-status/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configOrderStatus,
    });
  };
  const manufacturingConfigProcessTypesList = () => {
    return customAxios<ConfigProcessType[]>({
      url: `/api/manufacturing/config/process-types/`,
      method: "GET",
    });
  };
  const manufacturingConfigProcessTypesCreate = (
    configProcessType: NonReadonly<ConfigProcessType>,
  ) => {
    return customAxios<ConfigProcessType>({
      url: `/api/manufacturing/config/process-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configProcessType,
    });
  };
  const manufacturingConfigStepStatusList = () => {
    return customAxios<ConfigStepStatus[]>({
      url: `/api/manufacturing/config/step-status/`,
      method: "GET",
    });
  };
  const manufacturingConfigStepStatusCreate = (
    configStepStatus: NonReadonly<ConfigStepStatus>,
  ) => {
    return customAxios<ConfigStepStatus>({
      url: `/api/manufacturing/config/step-status/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configStepStatus,
    });
  };
  const manufacturingExecutionsList = () => {
    return customAxios<ProcessExecution[]>({
      url: `/api/manufacturing/executions/`,
      method: "GET",
    });
  };
  const manufacturingExecutionsCreate = (
    processExecution: NonReadonly<ProcessExecution>,
  ) => {
    return customAxios<ProcessExecution>({
      url: `/api/manufacturing/executions/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: processExecution,
    });
  };
  const manufacturingExecutionsRetrieve = (id: number) => {
    return customAxios<ProcessExecution>({
      url: `/api/manufacturing/executions/${id}/`,
      method: "GET",
    });
  };
  const manufacturingExecutionsUpdate = (
    id: number,
    processExecution: NonReadonly<ProcessExecution>,
  ) => {
    return customAxios<ProcessExecution>({
      url: `/api/manufacturing/executions/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: processExecution,
    });
  };
  const manufacturingExecutionsPartialUpdate = (
    id: number,
    patchedProcessExecution?: NonReadonly<PatchedProcessExecution>,
  ) => {
    return customAxios<ProcessExecution>({
      url: `/api/manufacturing/executions/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProcessExecution,
    });
  };
  const manufacturingExecutionsDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/executions/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingExecutionsExecuteCreate = (
    processExecution: NonReadonly<ProcessExecution>,
  ) => {
    return customAxios<ProcessExecution>({
      url: `/api/manufacturing/executions/execute/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: processExecution,
    });
  };
  const manufacturingMachineStatesList = () => {
    return customAxios<BaseMachineState[]>({
      url: `/api/manufacturing/machine-states/`,
      method: "GET",
    });
  };
  const manufacturingMachineStatesCreate = (
    baseMachineState: NonReadonly<BaseMachineState>,
  ) => {
    return customAxios<BaseMachineState>({
      url: `/api/manufacturing/machine-states/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: baseMachineState,
    });
  };
  const manufacturingMachineStatesRetrieve = (id: number) => {
    return customAxios<BaseMachineState>({
      url: `/api/manufacturing/machine-states/${id}/`,
      method: "GET",
    });
  };
  const manufacturingMachineStatesUpdate = (
    id: number,
    baseMachineState: NonReadonly<BaseMachineState>,
  ) => {
    return customAxios<BaseMachineState>({
      url: `/api/manufacturing/machine-states/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: baseMachineState,
    });
  };
  const manufacturingMachineStatesPartialUpdate = (
    id: number,
    patchedBaseMachineState?: NonReadonly<PatchedBaseMachineState>,
  ) => {
    return customAxios<BaseMachineState>({
      url: `/api/manufacturing/machine-states/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBaseMachineState,
    });
  };
  const manufacturingMachineStatesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/machine-states/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingMachineTypesList = () => {
    return customAxios<BaseMachineType[]>({
      url: `/api/manufacturing/machine-types/`,
      method: "GET",
    });
  };
  const manufacturingMachineTypesCreate = (
    baseMachineType: NonReadonly<BaseMachineType>,
  ) => {
    return customAxios<BaseMachineType>({
      url: `/api/manufacturing/machine-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: baseMachineType,
    });
  };
  const manufacturingMachineTypesRetrieve = (id: number) => {
    return customAxios<BaseMachineType>({
      url: `/api/manufacturing/machine-types/${id}/`,
      method: "GET",
    });
  };
  const manufacturingMachineTypesUpdate = (
    id: number,
    baseMachineType: NonReadonly<BaseMachineType>,
  ) => {
    return customAxios<BaseMachineType>({
      url: `/api/manufacturing/machine-types/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: baseMachineType,
    });
  };
  const manufacturingMachineTypesPartialUpdate = (
    id: number,
    patchedBaseMachineType?: NonReadonly<PatchedBaseMachineType>,
  ) => {
    return customAxios<BaseMachineType>({
      url: `/api/manufacturing/machine-types/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBaseMachineType,
    });
  };
  const manufacturingMachineTypesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/machine-types/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingMachinesList = () => {
    return customAxios<Machine[]>({
      url: `/api/manufacturing/machines/`,
      method: "GET",
    });
  };
  const manufacturingMachinesCreate = (machine: NonReadonly<Machine>) => {
    return customAxios<Machine>({
      url: `/api/manufacturing/machines/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: machine,
    });
  };
  const manufacturingMachinesRetrieve = (id: number) => {
    return customAxios<Machine>({
      url: `/api/manufacturing/machines/${id}/`,
      method: "GET",
    });
  };
  const manufacturingMachinesUpdate = (
    id: number,
    machine: NonReadonly<Machine>,
  ) => {
    return customAxios<Machine>({
      url: `/api/manufacturing/machines/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: machine,
    });
  };
  const manufacturingMachinesPartialUpdate = (
    id: number,
    patchedMachine?: NonReadonly<PatchedMachine>,
  ) => {
    return customAxios<Machine>({
      url: `/api/manufacturing/machines/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedMachine,
    });
  };
  const manufacturingMachinesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/machines/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingOrderPriorityList = () => {
    return customAxios<OrderPriority[]>({
      url: `/api/manufacturing/order-priority/`,
      method: "GET",
    });
  };
  const manufacturingOrderPriorityCreate = (
    orderPriority: NonReadonly<OrderPriority>,
  ) => {
    return customAxios<OrderPriority>({
      url: `/api/manufacturing/order-priority/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: orderPriority,
    });
  };
  const manufacturingOrderPriorityRetrieve = (id: number) => {
    return customAxios<OrderPriority>({
      url: `/api/manufacturing/order-priority/${id}/`,
      method: "GET",
    });
  };
  const manufacturingOrderPriorityUpdate = (
    id: number,
    orderPriority: NonReadonly<OrderPriority>,
  ) => {
    return customAxios<OrderPriority>({
      url: `/api/manufacturing/order-priority/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: orderPriority,
    });
  };
  const manufacturingOrderPriorityPartialUpdate = (
    id: number,
    patchedOrderPriority?: NonReadonly<PatchedOrderPriority>,
  ) => {
    return customAxios<OrderPriority>({
      url: `/api/manufacturing/order-priority/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedOrderPriority,
    });
  };
  const manufacturingOrderPriorityDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/order-priority/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingOrderStatusList = () => {
    return customAxios<OrderStatus[]>({
      url: `/api/manufacturing/order-status/`,
      method: "GET",
    });
  };
  const manufacturingOrderStatusCreate = (
    orderStatus: NonReadonly<OrderStatus>,
  ) => {
    return customAxios<OrderStatus>({
      url: `/api/manufacturing/order-status/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: orderStatus,
    });
  };
  const manufacturingOrderStatusRetrieve = (id: number) => {
    return customAxios<OrderStatus>({
      url: `/api/manufacturing/order-status/${id}/`,
      method: "GET",
    });
  };
  const manufacturingOrderStatusUpdate = (
    id: number,
    orderStatus: NonReadonly<OrderStatus>,
  ) => {
    return customAxios<OrderStatus>({
      url: `/api/manufacturing/order-status/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: orderStatus,
    });
  };
  const manufacturingOrderStatusPartialUpdate = (
    id: number,
    patchedOrderStatus?: NonReadonly<PatchedOrderStatus>,
  ) => {
    return customAxios<OrderStatus>({
      url: `/api/manufacturing/order-status/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedOrderStatus,
    });
  };
  const manufacturingOrderStatusDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/order-status/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingOrdersList = () => {
    return customAxios<ProductionOrder[]>({
      url: `/api/manufacturing/orders/`,
      method: "GET",
    });
  };
  const manufacturingOrdersCreate = (
    productionOrder: NonReadonly<ProductionOrder>,
  ) => {
    return customAxios<ProductionOrder>({
      url: `/api/manufacturing/orders/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productionOrder,
    });
  };
  const manufacturingOrdersRetrieve = (id: number) => {
    return customAxios<ProductionOrder>({
      url: `/api/manufacturing/orders/${id}/`,
      method: "GET",
    });
  };
  const manufacturingOrdersUpdate = (
    id: number,
    productionOrder: NonReadonly<ProductionOrder>,
  ) => {
    return customAxios<ProductionOrder>({
      url: `/api/manufacturing/orders/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: productionOrder,
    });
  };
  const manufacturingOrdersPartialUpdate = (
    id: number,
    patchedProductionOrder?: NonReadonly<PatchedProductionOrder>,
  ) => {
    return customAxios<ProductionOrder>({
      url: `/api/manufacturing/orders/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProductionOrder,
    });
  };
  const manufacturingOrdersDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/orders/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProcessTypesList = () => {
    return customAxios<ProcessType[]>({
      url: `/api/manufacturing/process-types/`,
      method: "GET",
    });
  };
  const manufacturingProcessTypesCreate = (
    processType: NonReadonly<ProcessType>,
  ) => {
    return customAxios<ProcessType>({
      url: `/api/manufacturing/process-types/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: processType,
    });
  };
  const manufacturingProcessTypesRetrieve = (id: number) => {
    return customAxios<ProcessType>({
      url: `/api/manufacturing/process-types/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProcessTypesUpdate = (
    id: number,
    processType: NonReadonly<ProcessType>,
  ) => {
    return customAxios<ProcessType>({
      url: `/api/manufacturing/process-types/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: processType,
    });
  };
  const manufacturingProcessTypesPartialUpdate = (
    id: number,
    patchedProcessType?: NonReadonly<PatchedProcessType>,
  ) => {
    return customAxios<ProcessType>({
      url: `/api/manufacturing/process-types/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProcessType,
    });
  };
  const manufacturingProcessTypesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/process-types/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProcessesList = () => {
    return customAxios<Process[]>({
      url: `/api/manufacturing/processes/`,
      method: "GET",
    });
  };
  const manufacturingProcessesCreate = (
    processCreate: NonReadonly<ProcessCreate>,
  ) => {
    return customAxios<ProcessCreate>({
      url: `/api/manufacturing/processes/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: processCreate,
    });
  };
  const manufacturingProcessesRetrieve = (id: number) => {
    return customAxios<Process>({
      url: `/api/manufacturing/processes/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProcessesUpdate = (
    id: number,
    processCreate: NonReadonly<ProcessCreate>,
  ) => {
    return customAxios<ProcessCreate>({
      url: `/api/manufacturing/processes/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: processCreate,
    });
  };
  const manufacturingProcessesPartialUpdate = (
    id: number,
    patchedProcessCreate?: NonReadonly<PatchedProcessCreate>,
  ) => {
    return customAxios<ProcessCreate>({
      url: `/api/manufacturing/processes/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProcessCreate,
    });
  };
  const manufacturingProcessesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/processes/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductionOrdersCreateCreate = (
    productionOrderCreate: NonReadonly<ProductionOrderCreate>,
  ) => {
    return customAxios<ProductionOrderCreate>({
      url: `/api/manufacturing/production-orders/create/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productionOrderCreate,
    });
  };

  type releaseBodyData = {
    confirm:boolean
  }

  const manufacturingProductionReleaseCreate = (id: number,bodyData:releaseBodyData) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/${id}/release/`,
      method: "POST",
      data:bodyData
    });
  };
  const manufacturingProductionBatchLinksList = () => {
    return customAxios<BatchLinkProduction[]>({
      url: `/api/manufacturing/production/batch-links/`,
      method: "GET",
    });
  };
  const manufacturingProductionBatchLinksCreate = (
    batchLinkProduction: NonReadonly<BatchLinkProduction>,
  ) => {
    return customAxios<BatchLinkProduction>({
      url: `/api/manufacturing/production/batch-links/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchLinkProduction,
    });
  };
  const manufacturingProductionBatchLinksRetrieve = (id: number) => {
    return customAxios<BatchLinkProduction>({
      url: `/api/manufacturing/production/batch-links/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductionBatchLinksUpdate = (
    id: number,
    batchLinkProduction: NonReadonly<BatchLinkProduction>,
  ) => {
    return customAxios<BatchLinkProduction>({
      url: `/api/manufacturing/production/batch-links/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: batchLinkProduction,
    });
  };
  const manufacturingProductionBatchLinksPartialUpdate = (
    id: number,
    patchedBatchLinkProduction?: NonReadonly<PatchedBatchLinkProduction>,
  ) => {
    return customAxios<BatchLinkProduction>({
      url: `/api/manufacturing/production/batch-links/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBatchLinkProduction,
    });
  };
  const manufacturingProductionBatchLinksDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/batch-links/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductionBatchesList = () => {
    return customAxios<BatchProduction[]>({
      url: `/api/manufacturing/production/batches/`,
      method: "GET",
    });
  };
  const manufacturingProductionBatchesCreate = (
    batchProduction: NonReadonly<BatchProduction>,
  ) => {
    return customAxios<BatchProduction>({
      url: `/api/manufacturing/production/batches/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchProduction,
    });
  };
  const manufacturingProductionBatchesRetrieve = (id: number) => {
    return customAxios<BatchProduction>({
      url: `/api/manufacturing/production/batches/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductionBatchesUpdate = (
    id: number,
    batchProduction: NonReadonly<BatchProduction>,
  ) => {
    return customAxios<BatchProduction>({
      url: `/api/manufacturing/production/batches/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: batchProduction,
    });
  };
  const manufacturingProductionBatchesPartialUpdate = (
    id: number,
    patchedBatchProduction?: NonReadonly<PatchedBatchProduction>,
  ) => {
    return customAxios<BatchProduction>({
      url: `/api/manufacturing/production/batches/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedBatchProduction,
    });
  };
  const manufacturingProductionBatchesDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/batches/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductionCreateFromProductCreate = () => {
    return customAxios<void>({
      url: `/api/manufacturing/production/create-from-product/`,
      method: "POST",
    });
  };
  const manufacturingProductionExecutionsList = () => {
    return customAxios<ProcessExecutionProduction[]>({
      url: `/api/manufacturing/production/executions/`,
      method: "GET",
    });
  };
  const manufacturingProductionExecutionsCreate = (
    processExecutionProduction: NonReadonly<ProcessExecutionProduction>,
  ) => {
    return customAxios<ProcessExecutionProduction>({
      url: `/api/manufacturing/production/executions/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: processExecutionProduction,
    });
  };
  const manufacturingProductionExecutionsRetrieve = (id: number) => {
    return customAxios<ProcessExecutionProduction>({
      url: `/api/manufacturing/production/executions/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductionExecutionsUpdate = (
    id: number,
    processExecutionProduction: NonReadonly<ProcessExecutionProduction>,
  ) => {
    return customAxios<ProcessExecutionProduction>({
      url: `/api/manufacturing/production/executions/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: processExecutionProduction,
    });
  };
  const manufacturingProductionExecutionsPartialUpdate = (
    id: number,
    patchedProcessExecutionProduction?: NonReadonly<PatchedProcessExecutionProduction>,
  ) => {
    return customAxios<ProcessExecutionProduction>({
      url: `/api/manufacturing/production/executions/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProcessExecutionProduction,
    });
  };
  const manufacturingProductionExecutionsDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/executions/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductionOrdersRetrieve = () => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/`,
      method: "GET",
    });
  };
  const manufacturingProductionOrdersCreate = () => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/`,
      method: "POST",
    });
  };
  const manufacturingProductionOrdersRetrieve2 = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductionOrdersUpdate = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/`,
      method: "PUT",
    });
  };
  const manufacturingProductionOrdersPartialUpdate = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/`,
      method: "PATCH",
    });
  };
  const manufacturingProductionOrdersDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductionOrdersFinishStepCreate = (
    id: number,
    stepId: string,
  ) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/finish-step/${stepId}/`,
      method: "POST",
    });
  };
  const manufacturingProductionOrdersReleaseCreate = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/release/`,
      method: "POST",
    });
  };
  const manufacturingProductionOrdersStartStepCreate = (
    id: number,
    stepId: string,
  ) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/${id}/start-step/${stepId}/`,
      method: "POST",
    });
  };
  const manufacturingProductionOrdersFromProductCreate = () => {
    return customAxios<void>({
      url: `/api/manufacturing/production/orders/from-product/`,
      method: "POST",
    });
  };
  const manufacturingProductionQualityList = () => {
    return customAxios<QualityInspectionProduction[]>({
      url: `/api/manufacturing/production/quality/`,
      method: "GET",
    });
  };
  const manufacturingProductionQualityCreate = (
    qualityInspectionProduction: NonReadonly<QualityInspectionProduction>,
  ) => {
    return customAxios<QualityInspectionProduction>({
      url: `/api/manufacturing/production/quality/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: qualityInspectionProduction,
    });
  };
  const manufacturingProductionQualityRetrieve = (id: number) => {
    return customAxios<QualityInspectionProduction>({
      url: `/api/manufacturing/production/quality/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductionQualityUpdate = (
    id: number,
    qualityInspectionProduction: NonReadonly<QualityInspectionProduction>,
  ) => {
    return customAxios<QualityInspectionProduction>({
      url: `/api/manufacturing/production/quality/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: qualityInspectionProduction,
    });
  };
  const manufacturingProductionQualityPartialUpdate = (
    id: number,
    patchedQualityInspectionProduction?: NonReadonly<PatchedQualityInspectionProduction>,
  ) => {
    return customAxios<QualityInspectionProduction>({
      url: `/api/manufacturing/production/quality/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedQualityInspectionProduction,
    });
  };
  const manufacturingProductionQualityDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/production/quality/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingProductsList = () => {
    return customAxios<Product[]>({
      url: `/api/manufacturing/products/`,
      method: "GET",
    });
  };
  const manufacturingProductsCreate = (
    productCreate: NonReadonly<ProductCreate>,
  ) => {
    return customAxios<ProductCreate>({
      url: `/api/manufacturing/products/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productCreate,
    });
  };
  const manufacturingProductsRetrieve = (id: number) => {
    return customAxios<Product>({
      url: `/api/manufacturing/products/${id}/`,
      method: "GET",
    });
  };
  const manufacturingProductsUpdate = (
    id: number,
    product: NonReadonly<Product>,
  ) => {
    return customAxios<Product>({
      url: `/api/manufacturing/products/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: product,
    });
  };
  const manufacturingProductsPartialUpdate = (
    id: number,
    patchedProduct?: NonReadonly<PatchedProduct>,
  ) => {
    return customAxios<Product>({
      url: `/api/manufacturing/products/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedProduct,
    });
  };
  const manufacturingProductsDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/products/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingQualityInspectionsList = () => {
    return customAxios<QualityInspectionDetailBase[]>({
      url: `/api/manufacturing/quality-inspections/`,
      method: "GET",
    });
  };
  const manufacturingQualityInspectionsCreate = (
    qualityInspectionBase: NonReadonly<QualityInspectionBase>,
  ) => {
    return customAxios<QualityInspectionBase>({
      url: `/api/manufacturing/quality-inspections/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: qualityInspectionBase,
    });
  };
  const manufacturingQualityInspectionsRetrieve = (id: number) => {
    return customAxios<QualityInspectionDetailBase>({
      url: `/api/manufacturing/quality-inspections/${id}/`,
      method: "GET",
    });
  };
  const manufacturingQualityInspectionsUpdate = (
    id: number,
    qualityInspectionBase: NonReadonly<QualityInspectionBase>,
  ) => {
    return customAxios<QualityInspectionBase>({
      url: `/api/manufacturing/quality-inspections/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: qualityInspectionBase,
    });
  };
  const manufacturingQualityInspectionsPartialUpdate = (
    id: number,
    patchedQualityInspectionBase?: NonReadonly<PatchedQualityInspectionBase>,
  ) => {
    return customAxios<QualityInspectionBase>({
      url: `/api/manufacturing/quality-inspections/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedQualityInspectionBase,
    });
  };
  const manufacturingQualityInspectionsDestroy = (id: number) => {
    return customAxios<void>({
      url: `/api/manufacturing/quality-inspections/${id}/`,
      method: "DELETE",
    });
  };
  const manufacturingSetupCreate = () => {
    return customAxios<void>({
      url: `/api/manufacturing/setup/`,
      method: "POST",
    });
  };
  return {
    manufacturingBatchLinksList,
    manufacturingBatchLinksRetrieve,
    manufacturingBatchesList,
    manufacturingBatchesCreate,
    manufacturingBatchesRetrieve,
    manufacturingBatchesUpdate,
    manufacturingBatchesPartialUpdate,
    manufacturingBatchesDestroy,
    manufacturingComponentTypesList,
    manufacturingComponentTypesCreate,
    manufacturingComponentTypesRetrieve,
    manufacturingComponentTypesUpdate,
    manufacturingComponentTypesPartialUpdate,
    manufacturingComponentTypesDestroy,
    manufacturingComponentsList,
    manufacturingComponentsCreate,
    manufacturingComponentsRetrieve,
    manufacturingComponentsUpdate,
    manufacturingComponentsPartialUpdate,
    manufacturingComponentsDestroy,
    manufacturingConfigComponentTypesList,
    manufacturingConfigComponentTypesCreate,
    manufacturingConfigMachineStatesList,
    manufacturingConfigMachineStatesCreate,
    manufacturingConfigMachineTypesList,
    manufacturingConfigMachineTypesCreate,
    manufacturingConfigOrderPrioritiesList,
    manufacturingConfigOrderPrioritiesCreate,
    manufacturingConfigOrderStatusList,
    manufacturingConfigOrderStatusCreate,
    manufacturingConfigProcessTypesList,
    manufacturingConfigProcessTypesCreate,
    manufacturingConfigStepStatusList,
    manufacturingConfigStepStatusCreate,
    manufacturingExecutionsList,
    manufacturingExecutionsCreate,
    manufacturingExecutionsRetrieve,
    manufacturingExecutionsUpdate,
    manufacturingExecutionsPartialUpdate,
    manufacturingExecutionsDestroy,
    manufacturingExecutionsExecuteCreate,
    manufacturingMachineStatesList,
    manufacturingMachineStatesCreate,
    manufacturingMachineStatesRetrieve,
    manufacturingMachineStatesUpdate,
    manufacturingMachineStatesPartialUpdate,
    manufacturingMachineStatesDestroy,
    manufacturingMachineTypesList,
    manufacturingMachineTypesCreate,
    manufacturingMachineTypesRetrieve,
    manufacturingMachineTypesUpdate,
    manufacturingMachineTypesPartialUpdate,
    manufacturingMachineTypesDestroy,
    manufacturingMachinesList,
    manufacturingMachinesCreate,
    manufacturingMachinesRetrieve,
    manufacturingMachinesUpdate,
    manufacturingMachinesPartialUpdate,
    manufacturingMachinesDestroy,
    manufacturingOrderPriorityList,
    manufacturingOrderPriorityCreate,
    manufacturingOrderPriorityRetrieve,
    manufacturingOrderPriorityUpdate,
    manufacturingOrderPriorityPartialUpdate,
    manufacturingOrderPriorityDestroy,
    manufacturingOrderStatusList,
    manufacturingOrderStatusCreate,
    manufacturingOrderStatusRetrieve,
    manufacturingOrderStatusUpdate,
    manufacturingOrderStatusPartialUpdate,
    manufacturingOrderStatusDestroy,
    manufacturingOrdersList,
    manufacturingOrdersCreate,
    manufacturingOrdersRetrieve,
    manufacturingOrdersUpdate,
    manufacturingOrdersPartialUpdate,
    manufacturingOrdersDestroy,
    manufacturingProcessTypesList,
    manufacturingProcessTypesCreate,
    manufacturingProcessTypesRetrieve,
    manufacturingProcessTypesUpdate,
    manufacturingProcessTypesPartialUpdate,
    manufacturingProcessTypesDestroy,
    manufacturingProcessesList,
    manufacturingProcessesCreate,
    manufacturingProcessesRetrieve,
    manufacturingProcessesUpdate,
    manufacturingProcessesPartialUpdate,
    manufacturingProcessesDestroy,
    manufacturingProductionOrdersCreateCreate,
    manufacturingProductionReleaseCreate,
    manufacturingProductionBatchLinksList,
    manufacturingProductionBatchLinksCreate,
    manufacturingProductionBatchLinksRetrieve,
    manufacturingProductionBatchLinksUpdate,
    manufacturingProductionBatchLinksPartialUpdate,
    manufacturingProductionBatchLinksDestroy,
    manufacturingProductionBatchesList,
    manufacturingProductionBatchesCreate,
    manufacturingProductionBatchesRetrieve,
    manufacturingProductionBatchesUpdate,
    manufacturingProductionBatchesPartialUpdate,
    manufacturingProductionBatchesDestroy,
    manufacturingProductionCreateFromProductCreate,
    manufacturingProductionExecutionsList,
    manufacturingProductionExecutionsCreate,
    manufacturingProductionExecutionsRetrieve,
    manufacturingProductionExecutionsUpdate,
    manufacturingProductionExecutionsPartialUpdate,
    manufacturingProductionExecutionsDestroy,
    manufacturingProductionOrdersRetrieve,
    manufacturingProductionOrdersCreate,
    manufacturingProductionOrdersRetrieve2,
    manufacturingProductionOrdersUpdate,
    manufacturingProductionOrdersPartialUpdate,
    manufacturingProductionOrdersDestroy,
    manufacturingProductionOrdersFinishStepCreate,
    manufacturingProductionOrdersReleaseCreate,
    manufacturingProductionOrdersStartStepCreate,
    manufacturingProductionOrdersFromProductCreate,
    manufacturingProductionQualityList,
    manufacturingProductionQualityCreate,
    manufacturingProductionQualityRetrieve,
    manufacturingProductionQualityUpdate,
    manufacturingProductionQualityPartialUpdate,
    manufacturingProductionQualityDestroy,
    manufacturingProductsList,
    manufacturingProductsCreate,
    manufacturingProductsRetrieve,
    manufacturingProductsUpdate,
    manufacturingProductsPartialUpdate,
    manufacturingProductsDestroy,
    manufacturingQualityInspectionsList,
    manufacturingQualityInspectionsCreate,
    manufacturingQualityInspectionsRetrieve,
    manufacturingQualityInspectionsUpdate,
    manufacturingQualityInspectionsPartialUpdate,
    manufacturingQualityInspectionsDestroy,
    manufacturingSetupCreate,
  };
};
