/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface BaseMachineState {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  display_name?: string;
  readonly created_at: string;
  /** @maxLength 7 */
  color?: string;
}
