/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface BatchLinkBase {
  readonly id: number;
  process_execution: number;
  input_batch: number;
  readonly input_batch_code: string;
  output_batch: number;
  readonly output_batch_code: string;
  /** @minimum 0.0001 */
  quantity: number;
}
