/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `quality` - quality
 * * `material` - material
 * * `maintenance` - maintenance
 */
export type BlockReasonEnum = typeof BlockReasonEnum[keyof typeof BlockReasonEnum];


export const BlockReasonEnum = {
  quality: 'quality',
  material: 'material',
  maintenance: 'maintenance',
} as const;
