/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { PlanEnum } from './planEnum';

export interface Client {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 20 */
  rut: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 20 */
  phone?: string;
  address?: string;
  plan?: PlanEnum;
  on_trial?: boolean;
  /** @nullable */
  paid_until?: string | null;
  readonly schema_name: string;
  is_active?: boolean;
}
