/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface ComponentProcess {
  readonly id: number;
  process: number;
  readonly process_name: string;
  /**
     * @minimum 0
     * @maximum 2147483647
     */
  order: number;
}
