/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { ComponentProcess } from './componentProcess';

export interface Component {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  code: string;
  description?: string;
  component_type: number;
  readonly component_type_name: string;
  readonly processes: readonly ComponentProcess[];
}
