/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface ConfigStepStatus {
  readonly id: number;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 50 */
  display_name?: string;
  /** @maxLength 7 */
  color?: string;
}
