/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface Machine {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  machine_type: number;
  readonly machine_type_name: string;
  state: number;
  readonly state_name: string;
  /** @nullable */
  assigned_to?: number | null;
  /** @maxLength 100 */
  location?: string;
}
