/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface OperatorMachineSession {
  readonly id: number;
  readonly operator_email: string;
  readonly machine_name: string;
  readonly started_at: string;
  /** @nullable */
  ended_at?: string | null;
  operator: number;
  machine: number;
}
