/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedProductionOrder {
  readonly id?: number;
  readonly product_name?: string;
  readonly status_name?: string;
  readonly priority_name?: string;
  /** @maxLength 100 */
  code?: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity?: number;
  start_date?: string;
  /** @nullable */
  end_date?: string | null;
  notes?: string;
  product?: number;
  priority?: number;
  status?: number;
}
