/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedUserCreate {
  readonly id?: number;
  /**
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     * @maxLength 150
     * @pattern ^[\w.@+-]+$
     */
  username?: string;
  /** @maxLength 254 */
  email?: string;
  password?: string;
  /** @nullable */
  role?: number | null;
}
