/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedProcessExecution {
  readonly id?: number;
  /** @nullable */
  process?: number | null;
  /** @nullable */
  machine?: number | null;
  /** @nullable */
  operator?: number | null;
  started_at?: string;
  /** @nullable */
  finished_at?: string | null;
  inputs?: unknown[];
  outputs?: unknown[];
}
