/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedProductionTask {
  readonly id?: number;
  readonly order_code?: string;
  readonly process_name?: string;
  readonly workstation_name?: string;
  readonly machine_name?: string;
  readonly operator_name?: string;
  /** @minimum 0 */
  planned_quantity?: number;
  /**
     * @minimum 0
     * @maximum 2147483647
     */
  priority?: number;
  notes?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  finished_at?: string | null;
  production_order?: number;
  step?: number;
  workstation?: number;
  /** @nullable */
  machine?: number | null;
  /** @nullable */
  operator?: number | null;
  /** @nullable */
  planned_component?: number | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  block_reason?: number | null;
}
