/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedBatchLinkProduction {
  readonly id?: number;
  /** @minimum 0.0001 */
  quantity?: number;
  process_execution?: number;
  input_batch?: number;
  output_batch?: number;
}
