/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedQualityInspectionProduction {
  readonly id?: number;
  notes?: string;
  readonly created_at?: string;
  /** @nullable */
  production_order?: number | null;
  /** @nullable */
  process_execution?: number | null;
  /** @nullable */
  batch?: number | null;
  status?: number;
  /** @nullable */
  inspected_by?: number | null;
}
