/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedWorkstation {
  readonly id?: number;
  readonly machine_type_name?: string;
  /** @maxLength 120 */
  name?: string;
  /** @maxLength 60 */
  code?: string;
  description?: string;
  is_active?: boolean;
  readonly created_at?: string;
  machine_type?: number;
}
