/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedUser {
  readonly id?: number;
  /**
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     * @maxLength 150
     * @pattern ^[\w.@+-]+$
     */
  username?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @maxLength 254 */
  email?: string;
  /** @nullable */
  role?: number | null;
  /** @nullable */
  tenant?: number | null;
  readonly is_platform_admin?: boolean;
  readonly is_company_admin?: boolean;
  is_active?: boolean;
}
