/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import { BlankEnum } from './blankEnum';
import { BlockReasonEnum } from './blockReasonEnum';

export const PatchedProductionTaskBlockReason = {...BlockReasonEnum,...BlankEnum,} as const