/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedBatchProduction {
  readonly id?: number;
  /** @maxLength 100 */
  code?: string;
  quantity?: number;
  readonly created_at?: string;
  product?: number;
  /** @nullable */
  production_order?: number | null;
}
