/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedComponent {
  readonly id?: number;
  readonly component_type_name?: string;
  /** @maxLength 100 */
  name?: string;
  /** @maxLength 100 */
  code?: string;
  description?: string;
  component_type?: number;
}
