/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { ProcessStep } from './processStep';

export interface Process {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  process_type: number;
  description?: string;
  readonly steps: readonly ProcessStep[];
}
