/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface ProcessExecutionProduction {
  readonly id: number;
  started_at: string;
  /** @nullable */
  finished_at?: string | null;
  notes?: string;
  production_order: number;
  /** @nullable */
  machine?: number | null;
  /** @nullable */
  component?: number | null;
  /** @nullable */
  process?: number | null;
  /** @nullable */
  step?: number | null;
  /** @nullable */
  operator?: number | null;
}
