/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface ProductionOrderCreate {
  readonly id: number;
  product: number;
  /** @maxLength 100 */
  code: string;
  status: number;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity: number;
  priority: number;
  start_date: string;
  notes?: string;
}
