/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductComponent } from './productComponent';
import type { ProductProcess } from './productProcess';

export interface Product {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  code: string;
  description?: string;
  readonly components: readonly ProductComponent[];
  readonly processes: readonly ProductProcess[];
}
