/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface QualityInspectionBase {
  readonly id: number;
  /** @nullable */
  process_execution?: number | null;
  /** @nullable */
  batch?: number | null;
  status: number;
  notes?: string;
  /** @nullable */
  readonly inspected_by: number | null;
  readonly created_at: string;
}
