/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaRetrieveFormat } from './schemaRetrieveFormat';
import type { SchemaRetrieveLang } from './schemaRetrieveLang';

export type SchemaRetrieveParams = {
format?: SchemaRetrieveFormat;
lang?: SchemaRetrieveLang;
};
