/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `queued` - queued
 * * `assigned` - assigned
 * * `in_progress` - in_progress
 * * `paused` - paused
 * * `blocked` - blocked
 * * `done` - done
 * * `cancelled` - cancelled
 */
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


export const StatusEnum = {
  queued: 'queued',
  assigned: 'assigned',
  in_progress: 'in_progress',
  paused: 'paused',
  blocked: 'blocked',
  done: 'done',
  cancelled: 'cancelled',
} as const;
