/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

import type { User } from "./user";
import type { UserLoginRespose } from "./userLogin";

export interface UserRegistration {
  readonly id: number;
  /**
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     * @maxLength 150
     * @pattern ^[\w.@+-]+$
     */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 128 */
  password: string;
  password_confirm: string;
}

export interface UserRegistrationRespose extends Pick<User,"id"|"username"|"email">,Pick<UserLoginRespose,'tokens'> {}