/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { PlanEnum } from './planEnum';

export interface ClientCreate {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 20 */
  rut: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 20 */
  phone?: string;
  address?: string;
  plan?: PlanEnum;
  on_trial?: boolean;
  /** @nullable */
  paid_until?: string | null;
  domain: string;
  readonly admin_credentials: string;
}
