/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedUserRoleCreate {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  can_manage_users?: boolean;
  can_manage_production?: boolean;
}
