/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `basic` - Básico
* `professional` - Profesional
* `enterprise` - Empresarial
 */
export type PlanEnum = typeof PlanEnum[keyof typeof PlanEnum];


export const PlanEnum = {
  basic: 'basic',
  professional: 'professional',
  enterprise: 'enterprise',
} as const;
