/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

export interface ProcessStep {
  readonly id: number;
  /**
     * @minimum 0
     * @maximum 2147483647
     * @nullable
     */
  order?: number | null;
  /** @nullable */
  machine?: number | null;
  readonly machine_name: string;
  description?: string;
}
