/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */
import type { ProcessStep } from './processStep';

export interface ProcessCreate {
  /** @maxLength 100 */
  name: string;
  process_type: number;
  description?: string;
  steps: ProcessStep[];
}
