/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * ADC-System API
 * API documentation for your project
 * OpenAPI spec version: 1.0.0
 */

import type { User } from "./user";

export interface UserLogin {
  email: string;
  password: string;
}

export interface UserLoginRespose extends User {
  tokens:{
    access:string;
    refresh:string;
  }
}
